version: "3"

includes:
  homebrew:
    taskfile: ./homebrew/Taskfile.yml
    dir: ./homebrew

tasks:
  init:
    cmds:
      - task: homebrew
      - task: aqua-install
  aqua-install:
    cmd: aqua i -l
  brew-dump:
    cmds:
      - task: homebrew:dump