version: "3"

tasks:
  default:
    cmds:
      - brew bundle --file=Brewfile --force
  install:
    cmds:
      - brew bundle --file=Brewfile
  dump:
    cmds:
      - brew bundle dump --file=Brewfile --force
